// GENERATED by scripts/gen-aliases.mjs — do not edit by hand.
/** Vitest runtime aliases resolving @deepseek-ai/* to the checkout's built lib. */
export declare const aliases: readonly { find: RegExp; replacement: string }[]
