/**
 * Generate the harness-package resolution maps for this external plugin:
 * `tsconfig.paths.json` (typecheck against the checkout's built declarations)
 * and `vitest.aliases.mjs` (resolve `@deepseek-ai/*` at runtime from the
 * checkout's built lib). Both are committed so CI/test runs do not need the
 * generator; re-run after the harness checkout moves.
 *
 * Each package contributes one anchored bare-name entry plus one anchored
 * entry per `exports` subpath that maps to a runtime JS file — vite's alias
 * replaces literal prefixes only, so subpaths need their own rows and the
 * anchored regex keeps a shorter name from swallowing a longer one.
 *
 * Scans `packages/**&#47;package.json` and `vendor/**&#47;package.json` under the
 * harness root (three levels above this plugin directory).
 * @module gen-aliases
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pluginRoot = resolve(here, '..')
// CI clones the harness to an arbitrary location and maps paths through
// DSH_HARNESS_ROOT; local development keeps the sibling-checkout default
// (three levels above the plugin directory).
const harnessRoot = process.env.DSH_HARNESS_ROOT
  ? resolve(process.env.DSH_HARNESS_ROOT)
  : resolve(pluginRoot, '..', '..', '..')

/** Recursively collect `name -> package dir` for every scoped harness package. */
function collectHarnessPackages() {
  const result = new Map()
  for (const root of ['packages', 'vendor']) {
    walk(join(harnessRoot, root))
  }
  return result

  function walk(dir) {
    let entries
    try {
      entries = readdirSync(dir)
    } catch {
      return
    }
    for (const entry of entries) {
      const full = join(dir, entry)
      if (entry === 'node_modules' || entry.startsWith('.')) continue
      let isDir = false
      try {
        isDir = statSync(full).isDirectory()
      } catch {
        continue
      }
      if (!isDir) continue
      const manifest = join(full, 'package.json')
      try {
        const pkg = JSON.parse(readFileSync(manifest, 'utf8'))
        if (typeof pkg.name === 'string' && pkg.name.startsWith('@deepseek-ai/')) {
          result.set(pkg.name, { dir: full, pkg })
        }
      } catch {
        /* directory without a readable manifest — keep walking */
      }
      walk(full)
    }
  }
}

/** Resolve one exports target to an absolute file path, when it names a runtime JS file. */
function runtimeTarget(dir, target) {
  if (typeof target === 'string') return join(dir, target)
  if (typeof target === 'object' && target !== null) {
    const value = target.default ?? target.import ?? target.require
    if (typeof value === 'string') return join(dir, value)
  }
  return undefined
}

const packages = collectHarnessPackages()
const rows = [] // { name, typeFile, runtime: Map<subpath, file> }
for (const [name, { dir, pkg }] of [...packages].sort(([a], [b]) => (a < b ? -1 : 1))) {
  const typesDir = join(dir, 'lib/types')
  const typeFile = typeof pkg.types === 'string' ? join(dir, pkg.types) : join(typesDir, 'index.d.ts')
  const runtime = new Map()
  const main = runtimeTarget(dir, pkg.main) ?? join(dir, 'lib/index.js')
  runtime.set('', main)
  const exports = pkg.exports
  if (typeof exports === 'object' && exports !== null) {
    for (const [key, target] of Object.entries(exports)) {
      if (!key.startsWith('./')) continue
      const sub = key.slice(2)
      if (sub.includes('*') || sub === '') continue
      const file = runtimeTarget(dir, target)
      if (file !== undefined) runtime.set(sub, file)
    }
  }
  rows.push({ name, typeFile, runtime })
}

const rel = file => relative(pluginRoot, file).replaceAll('\\', '/')

const pathEntries = []
const aliasEntries = []
for (const row of rows) {
  const relTypes = rel(row.typeFile)
  pathEntries.push(`      ${JSON.stringify(`${row.name}/*`)}: [${JSON.stringify(`${rel(dirname(row.typeFile))}/*`)}],`)
  pathEntries.push(`      ${JSON.stringify(row.name)}: [${JSON.stringify(relTypes)}],`)
  for (const [sub, file] of row.runtime) {
    const spec = sub === '' ? row.name : `${row.name}/${sub}`
    // A regex literal in the generated module: anchor the specifier so a
    // shorter name never prefix-matches a longer one, escaping its syntax.
    const findLiteral = `/^${spec.replace(/[.\\/]/g, char => `\\${char}`)}$/`
    aliasEntries.push(`  { find: ${findLiteral}, replacement: ${JSON.stringify(file.replaceAll('\\', '/'))} },`)
  }
}

const pathsJson = `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
${pathEntries.join('\n')}
      "zod": ["./node_modules/zod"]
    }
  }
}
`

const aliasesMjs = `// GENERATED by scripts/gen-aliases.mjs — do not edit by hand.
/** Vitest runtime aliases resolving @deepseek-ai/* to the checkout's built lib (anchored per entry). */
export const aliases = [
${aliasEntries.join('\n')}
]
`

writeFileSync(join(pluginRoot, 'tsconfig.paths.json'), pathsJson)
writeFileSync(join(pluginRoot, 'vitest.aliases.mjs'), aliasesMjs)
writeFileSync(join(pluginRoot, 'vitest.aliases.d.mts'), `// GENERATED by scripts/gen-aliases.mjs — do not edit by hand.
/** Vitest runtime aliases resolving @deepseek-ai/* to the checkout's built lib. */
export declare const aliases: readonly { find: RegExp; replacement: string }[]
`)
console.log(`gen-aliases: mapped ${packages.size} harness packages, ${aliasEntries.length} runtime aliases`)
